[package]
name = "ft8rs"
version = "0.0.0"
edition = "2021"
description = "FT8 streaming decoder"
license = "GPL-3.0"

[[bin]]
name = "ft8rs"
path = "src/main.rs"

[features]
default = []
# Compile-time: default rustfft@3840. Enable fftw for FFTW@3840 validation.
fftw = []

[dependencies]
rayon = "1"
rustfft = "6"

hound = "3"
num-bigint = "0.4"
num-complex = "0.4"
num-traits = "0.2"
clap = { version = "4", features = ["derive"] }
cpal = "0.15"
