[package]
name = "ft8rs-gui"
version = "0.0.0"
edition = "2021"
license = "GPL-3.0"
description = "FT8 streaming decoder GUI (egui)"

[[bin]]
name = "ft8rs-gui"
path = "src/main.rs"

[dependencies]
ft8rs-core = { path = "../ft8rs-core" }
ft8rs-engine = { path = "../ft8rs-engine" }
eframe = "0.29"
muda = "0.15"

[build-dependencies]
ft8rs-build = { path = "../ft8rs-build" }

[features]
default = []
fftw = ["ft8rs-core/fftw", "ft8rs-engine/fftw"]
